/*
 * generated by Xtext
 */
package rslingo.rslil.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class RSLILUiModule extends rslingo.rslil.ui.AbstractRSLILUiModule {
	public RSLILUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
