/*
 * generated by Xtext
 */
package rslingo.rslil.validation

import org.eclipse.xtext.validation.Check
import rslingo.rslil.rSLIL.NFR
import rslingo.rslil.rSLIL.RSLILPackage
import rslingo.rslil.rSLIL.UseCase
import rslingo.rslil.rSLIL.EntityType
import rslingo.rslil.rSLIL.Step

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class RSLILValidator extends AbstractRSLILValidator {

	@Check
	def checkUseCaseEntities(UseCase uc) {
		if (!uc.type.equals("Report")) {
			if (uc.entities == null) {
				error('A Use Case of type \'' + uc.type + '\' should be associated to an Entity with the role Master.', RSLILPackage.Literals.USE_CASE__ENTITIES)	
			} else {
				if (!uc.entities.type.type.equals("Master")) {
					if (uc.entities.refs.isEmpty()) {
						error('A Use Case of type \'' + uc.type + '\' should be associated to an Entity with the role Master.', RSLILPackage.Literals.USE_CASE__ENTITIES)		
					} else {
						var hasMaster = false
						
						for (EntityType type : uc.entities.refType) {
							if (type.type.equals("Master")) {
								hasMaster = true
							}
						}
						
						if (!hasMaster) {
							error('A Use Case of type \'' + uc.type + '\' should be associated to an Entity with the role Master.', RSLILPackage.Literals.USE_CASE__ENTITIES)	
						}
					}
				}
			}
		}
	}
	
	@Check
	def checkStepName(Step step) {
		if (step.name != null) {
			var parts = step.name.split("s")
			
			if (parts.size == 2 && parts.get(0).empty) {
				try {
					Integer.parseInt(parts.get(1))
				} catch (Exception e) {
					error('The Step name must be in the format \'s<integer>\'.', RSLILPackage.Literals.STEP__NAME)	
				}
			} else {
				error('The Step name must be in the format \'s<integer>\'.', RSLILPackage.Literals.STEP__NAME)
			}
		}
	}
	
	@Check
	def checkNFRSubType(NFR nfr) {
		if (nfr.subType != null) {
			if (nfr.type.equals("Security")) {
				if (!nfr.subType.equals("Security.Privacy")
					&& !nfr.subType.equals("Security.Integrity")) {
					error('A Non-FunctionalRequirement of type \'Security\' can only have the following sub-types: Security.Privacy or Security.Integrity.', RSLILPackage.Literals.NFR__SUB_TYPE)	
				}	
			} else if (nfr.type.equals("Usability")) {
				if (!nfr.subType.equals("Usability.EaseOfUse")
					&& !nfr.subType.equals("Usability.EaseOfLearn")
					&& !nfr.subType.equals("Usability.Accessibility")) {
					error('A Non-FunctionalRequirement of type \'Usability\' can only have the following sub-types: Usability.EaseOfUse, Usability.EaseOfLearn or Usability.Accessibility.', RSLILPackage.Literals.NFR__SUB_TYPE)	
				}
			} else {
				// Don't allow Sub-Type when Type != of Security and Usability
				error('A Non-FunctionalRequirement of type \'' + nfr.type + '\' cannot have a sub-type.', RSLILPackage.Literals.NFR__SUB_TYPE)		
			}
		}
	}
}
