/*
 * generated by Xtext
 */
package rslingo.rslil.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class RSLILGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class ModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Model");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cSystemsAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cSystemsSystemParserRuleCall_0_0 = (RuleCall)cSystemsAssignment_0.eContents().get(0);
		private final Assignment cGlossariesAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cGlossariesGlossaryParserRuleCall_1_0 = (RuleCall)cGlossariesAssignment_1.eContents().get(0);
		private final Assignment cStakeholdersAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cStakeholdersStakeholderParserRuleCall_2_0 = (RuleCall)cStakeholdersAssignment_2.eContents().get(0);
		private final Assignment cGoalsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cGoalsGoalParserRuleCall_3_0 = (RuleCall)cGoalsAssignment_3.eContents().get(0);
		
		//Model: // Business Level
		//	systems+=System* glossaries+=Glossary* stakeholders+=Stakeholder* goals+=Goal*;
		@Override public ParserRule getRule() { return rule; }

		//// Business Level
		//systems+=System* glossaries+=Glossary* stakeholders+=Stakeholder* goals+=Goal*
		public Group getGroup() { return cGroup; }

		//// Business Level
		//systems+=System*
		public Assignment getSystemsAssignment_0() { return cSystemsAssignment_0; }

		//System
		public RuleCall getSystemsSystemParserRuleCall_0_0() { return cSystemsSystemParserRuleCall_0_0; }

		//glossaries+=Glossary*
		public Assignment getGlossariesAssignment_1() { return cGlossariesAssignment_1; }

		//Glossary
		public RuleCall getGlossariesGlossaryParserRuleCall_1_0() { return cGlossariesGlossaryParserRuleCall_1_0; }

		//stakeholders+=Stakeholder*
		public Assignment getStakeholdersAssignment_2() { return cStakeholdersAssignment_2; }

		//Stakeholder
		public RuleCall getStakeholdersStakeholderParserRuleCall_2_0() { return cStakeholdersStakeholderParserRuleCall_2_0; }

		//goals+=Goal*
		public Assignment getGoalsAssignment_3() { return cGoalsAssignment_3; }

		//Goal
		public RuleCall getGoalsGoalParserRuleCall_3_0() { return cGoalsGoalParserRuleCall_3_0; }
	}

	public class SystemElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "System");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSystemKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cIdAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cIdIDTerminalRuleCall_1_0 = (RuleCall)cIdAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cIdKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cSystemIdAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cSystemIdSTRINGTerminalRuleCall_4_0 = (RuleCall)cSystemIdAssignment_4.eContents().get(0);
		private final Keyword cNameKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cNameAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cNameSTRINGTerminalRuleCall_6_0 = (RuleCall)cNameAssignment_6.eContents().get(0);
		private final Keyword cDescriptionKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cDescriptionAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cDescriptionSTRINGTerminalRuleCall_8_0 = (RuleCall)cDescriptionAssignment_8.eContents().get(0);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cDecomposedByKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Assignment cRefSystemAssignment_9_1 = (Assignment)cGroup_9.eContents().get(1);
		private final RuleCall cRefSystemRefSystemParserRuleCall_9_1_0 = (RuleCall)cRefSystemAssignment_9_1.eContents().get(0);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Keyword cPartOfKeyword_10_0 = (Keyword)cGroup_10.eContents().get(0);
		private final Assignment cPartOfAssignment_10_1 = (Assignment)cGroup_10.eContents().get(1);
		private final CrossReference cPartOfSystemCrossReference_10_1_0 = (CrossReference)cPartOfAssignment_10_1.eContents().get(0);
		private final RuleCall cPartOfSystemIDTerminalRuleCall_10_1_0_1 = (RuleCall)cPartOfSystemCrossReference_10_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_11 = (Keyword)cGroup.eContents().get(11);
		
		//// TODO System Level
		//System:
		//	"System" id=ID "{" "Id" systemId=STRING "Name" name=STRING "Description" description=STRING ("DecomposedBy"
		//	refSystem=RefSystem)? ("PartOf" partOf=[System])? "}";
		@Override public ParserRule getRule() { return rule; }

		//"System" id=ID "{" "Id" systemId=STRING "Name" name=STRING "Description" description=STRING ("DecomposedBy"
		//refSystem=RefSystem)? ("PartOf" partOf=[System])? "}"
		public Group getGroup() { return cGroup; }

		//"System"
		public Keyword getSystemKeyword_0() { return cSystemKeyword_0; }

		//id=ID
		public Assignment getIdAssignment_1() { return cIdAssignment_1; }

		//ID
		public RuleCall getIdIDTerminalRuleCall_1_0() { return cIdIDTerminalRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//"Id"
		public Keyword getIdKeyword_3() { return cIdKeyword_3; }

		//systemId=STRING
		public Assignment getSystemIdAssignment_4() { return cSystemIdAssignment_4; }

		//STRING
		public RuleCall getSystemIdSTRINGTerminalRuleCall_4_0() { return cSystemIdSTRINGTerminalRuleCall_4_0; }

		//"Name"
		public Keyword getNameKeyword_5() { return cNameKeyword_5; }

		//name=STRING
		public Assignment getNameAssignment_6() { return cNameAssignment_6; }

		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_6_0() { return cNameSTRINGTerminalRuleCall_6_0; }

		//"Description"
		public Keyword getDescriptionKeyword_7() { return cDescriptionKeyword_7; }

		//description=STRING
		public Assignment getDescriptionAssignment_8() { return cDescriptionAssignment_8; }

		//STRING
		public RuleCall getDescriptionSTRINGTerminalRuleCall_8_0() { return cDescriptionSTRINGTerminalRuleCall_8_0; }

		//("DecomposedBy" refSystem=RefSystem)?
		public Group getGroup_9() { return cGroup_9; }

		//"DecomposedBy"
		public Keyword getDecomposedByKeyword_9_0() { return cDecomposedByKeyword_9_0; }

		//refSystem=RefSystem
		public Assignment getRefSystemAssignment_9_1() { return cRefSystemAssignment_9_1; }

		//RefSystem
		public RuleCall getRefSystemRefSystemParserRuleCall_9_1_0() { return cRefSystemRefSystemParserRuleCall_9_1_0; }

		//("PartOf" partOf=[System])?
		public Group getGroup_10() { return cGroup_10; }

		//"PartOf"
		public Keyword getPartOfKeyword_10_0() { return cPartOfKeyword_10_0; }

		//partOf=[System]
		public Assignment getPartOfAssignment_10_1() { return cPartOfAssignment_10_1; }

		//[System]
		public CrossReference getPartOfSystemCrossReference_10_1_0() { return cPartOfSystemCrossReference_10_1_0; }

		//ID
		public RuleCall getPartOfSystemIDTerminalRuleCall_10_1_0_1() { return cPartOfSystemIDTerminalRuleCall_10_1_0_1; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_11() { return cRightCurlyBracketKeyword_11; }
	}

	public class RefSystemElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "RefSystem");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cRefSystemAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final CrossReference cRefSystemSystemCrossReference_0_0 = (CrossReference)cRefSystemAssignment_0.eContents().get(0);
		private final RuleCall cRefSystemSystemIDTerminalRuleCall_0_0_1 = (RuleCall)cRefSystemSystemCrossReference_0_0.eContents().get(1);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cCommaKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cRefsAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final CrossReference cRefsSystemCrossReference_1_1_0 = (CrossReference)cRefsAssignment_1_1.eContents().get(0);
		private final RuleCall cRefsSystemIDTerminalRuleCall_1_1_0_1 = (RuleCall)cRefsSystemCrossReference_1_1_0.eContents().get(1);
		
		//RefSystem:
		//	refSystem=[System] ("," refs+=[System])*;
		@Override public ParserRule getRule() { return rule; }

		//refSystem=[System] ("," refs+=[System])*
		public Group getGroup() { return cGroup; }

		//refSystem=[System]
		public Assignment getRefSystemAssignment_0() { return cRefSystemAssignment_0; }

		//[System]
		public CrossReference getRefSystemSystemCrossReference_0_0() { return cRefSystemSystemCrossReference_0_0; }

		//ID
		public RuleCall getRefSystemSystemIDTerminalRuleCall_0_0_1() { return cRefSystemSystemIDTerminalRuleCall_0_0_1; }

		//("," refs+=[System])*
		public Group getGroup_1() { return cGroup_1; }

		//","
		public Keyword getCommaKeyword_1_0() { return cCommaKeyword_1_0; }

		//refs+=[System]
		public Assignment getRefsAssignment_1_1() { return cRefsAssignment_1_1; }

		//[System]
		public CrossReference getRefsSystemCrossReference_1_1_0() { return cRefsSystemCrossReference_1_1_0; }

		//ID
		public RuleCall getRefsSystemIDTerminalRuleCall_1_1_0_1() { return cRefsSystemIDTerminalRuleCall_1_1_0_1; }
	}

	public class GlossaryElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Glossary");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cGlossaryKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cIdAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cIdIDTerminalRuleCall_1_0 = (RuleCall)cIdAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cNameKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cNameAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cNameSTRINGTerminalRuleCall_4_0 = (RuleCall)cNameAssignment_4.eContents().get(0);
		private final Keyword cTypeKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cTypeAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cTypeSTRINGTerminalRuleCall_6_0 = (RuleCall)cTypeAssignment_6.eContents().get(0);
		private final Keyword cAcronymKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cAcronymAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cAcronymSTRINGTerminalRuleCall_8_0 = (RuleCall)cAcronymAssignment_8.eContents().get(0);
		private final Keyword cDescriptionKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cDescriptionAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cDescriptionSTRINGTerminalRuleCall_10_0 = (RuleCall)cDescriptionAssignment_10.eContents().get(0);
		private final Keyword cPOSKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Assignment cPosAssignment_12 = (Assignment)cGroup.eContents().get(12);
		private final RuleCall cPosSTRINGTerminalRuleCall_12_0 = (RuleCall)cPosAssignment_12.eContents().get(0);
		private final Keyword cSynsetKeyword_13 = (Keyword)cGroup.eContents().get(13);
		private final Assignment cSynsetAssignment_14 = (Assignment)cGroup.eContents().get(14);
		private final RuleCall cSynsetSTRINGTerminalRuleCall_14_0 = (RuleCall)cSynsetAssignment_14.eContents().get(0);
		private final Keyword cTermRelationTypeKeyword_15 = (Keyword)cGroup.eContents().get(15);
		private final Assignment cTermRelationTypeAssignment_16 = (Assignment)cGroup.eContents().get(16);
		private final RuleCall cTermRelationTypeSTRINGTerminalRuleCall_16_0 = (RuleCall)cTermRelationTypeAssignment_16.eContents().get(0);
		private final Keyword cTermRelationKeyword_17 = (Keyword)cGroup.eContents().get(17);
		private final Assignment cTermRelationAssignment_18 = (Assignment)cGroup.eContents().get(18);
		private final RuleCall cTermRelationSTRINGTerminalRuleCall_18_0 = (RuleCall)cTermRelationAssignment_18.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_19 = (Keyword)cGroup.eContents().get(19);
		
		//Glossary:
		//	"Glossary" id=ID "{" "Name" name=STRING "Type" type=STRING "Acronym" acronym=STRING "Description" description=STRING
		//	"POS" pos=STRING "Synset" synset=STRING "TermRelationType" termRelationType=STRING "TermRelation" termRelation=STRING
		//	"}";
		@Override public ParserRule getRule() { return rule; }

		//"Glossary" id=ID "{" "Name" name=STRING "Type" type=STRING "Acronym" acronym=STRING "Description" description=STRING
		//"POS" pos=STRING "Synset" synset=STRING "TermRelationType" termRelationType=STRING "TermRelation" termRelation=STRING
		//"}"
		public Group getGroup() { return cGroup; }

		//"Glossary"
		public Keyword getGlossaryKeyword_0() { return cGlossaryKeyword_0; }

		//id=ID
		public Assignment getIdAssignment_1() { return cIdAssignment_1; }

		//ID
		public RuleCall getIdIDTerminalRuleCall_1_0() { return cIdIDTerminalRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//"Name"
		public Keyword getNameKeyword_3() { return cNameKeyword_3; }

		//name=STRING
		public Assignment getNameAssignment_4() { return cNameAssignment_4; }

		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_4_0() { return cNameSTRINGTerminalRuleCall_4_0; }

		//"Type"
		public Keyword getTypeKeyword_5() { return cTypeKeyword_5; }

		//type=STRING
		public Assignment getTypeAssignment_6() { return cTypeAssignment_6; }

		//STRING
		public RuleCall getTypeSTRINGTerminalRuleCall_6_0() { return cTypeSTRINGTerminalRuleCall_6_0; }

		//"Acronym"
		public Keyword getAcronymKeyword_7() { return cAcronymKeyword_7; }

		//acronym=STRING
		public Assignment getAcronymAssignment_8() { return cAcronymAssignment_8; }

		//STRING
		public RuleCall getAcronymSTRINGTerminalRuleCall_8_0() { return cAcronymSTRINGTerminalRuleCall_8_0; }

		//"Description"
		public Keyword getDescriptionKeyword_9() { return cDescriptionKeyword_9; }

		//description=STRING
		public Assignment getDescriptionAssignment_10() { return cDescriptionAssignment_10; }

		//STRING
		public RuleCall getDescriptionSTRINGTerminalRuleCall_10_0() { return cDescriptionSTRINGTerminalRuleCall_10_0; }

		//"POS"
		public Keyword getPOSKeyword_11() { return cPOSKeyword_11; }

		//pos=STRING
		public Assignment getPosAssignment_12() { return cPosAssignment_12; }

		//STRING
		public RuleCall getPosSTRINGTerminalRuleCall_12_0() { return cPosSTRINGTerminalRuleCall_12_0; }

		//"Synset"
		public Keyword getSynsetKeyword_13() { return cSynsetKeyword_13; }

		//synset=STRING
		public Assignment getSynsetAssignment_14() { return cSynsetAssignment_14; }

		//STRING
		public RuleCall getSynsetSTRINGTerminalRuleCall_14_0() { return cSynsetSTRINGTerminalRuleCall_14_0; }

		//"TermRelationType"
		public Keyword getTermRelationTypeKeyword_15() { return cTermRelationTypeKeyword_15; }

		//termRelationType=STRING
		public Assignment getTermRelationTypeAssignment_16() { return cTermRelationTypeAssignment_16; }

		//STRING
		public RuleCall getTermRelationTypeSTRINGTerminalRuleCall_16_0() { return cTermRelationTypeSTRINGTerminalRuleCall_16_0; }

		//"TermRelation"
		public Keyword getTermRelationKeyword_17() { return cTermRelationKeyword_17; }

		//termRelation=STRING
		public Assignment getTermRelationAssignment_18() { return cTermRelationAssignment_18; }

		//STRING
		public RuleCall getTermRelationSTRINGTerminalRuleCall_18_0() { return cTermRelationSTRINGTerminalRuleCall_18_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_19() { return cRightCurlyBracketKeyword_19; }
	}

	public class StakeholderElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Stakeholder");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cStakeholderKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cIdAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cIdIDTerminalRuleCall_1_0 = (RuleCall)cIdAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cNameKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cNameAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cNameSTRINGTerminalRuleCall_4_0 = (RuleCall)cNameAssignment_4.eContents().get(0);
		private final Keyword cTypeKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cTypeAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cTypeSTRINGTerminalRuleCall_6_0 = (RuleCall)cTypeAssignment_6.eContents().get(0);
		private final Keyword cCategoryKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cCotegoryAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cCotegorySTRINGTerminalRuleCall_8_0 = (RuleCall)cCotegoryAssignment_8.eContents().get(0);
		private final Keyword cDescriptionKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cDescriptionAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cDescriptionSTRINGTerminalRuleCall_10_0 = (RuleCall)cDescriptionAssignment_10.eContents().get(0);
		private final Keyword cDependsOnTypeKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Assignment cDependsOnTypeAssignment_12 = (Assignment)cGroup.eContents().get(12);
		private final RuleCall cDependsOnTypeSTRINGTerminalRuleCall_12_0 = (RuleCall)cDependsOnTypeAssignment_12.eContents().get(0);
		private final Keyword cDependsOnKeyword_13 = (Keyword)cGroup.eContents().get(13);
		private final Assignment cDependsOnAssignment_14 = (Assignment)cGroup.eContents().get(14);
		private final RuleCall cDependsOnSTRINGTerminalRuleCall_14_0 = (RuleCall)cDependsOnAssignment_14.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_15 = (Keyword)cGroup.eContents().get(15);
		
		//Stakeholder:
		//	"Stakeholder" id=ID "{" "Name" name=STRING "Type" type=STRING "Category" cotegory=STRING "Description"
		//	description=STRING "DependsOnType" dependsOnType=STRING "DependsOn" dependsOn=STRING "}";
		@Override public ParserRule getRule() { return rule; }

		//"Stakeholder" id=ID "{" "Name" name=STRING "Type" type=STRING "Category" cotegory=STRING "Description"
		//description=STRING "DependsOnType" dependsOnType=STRING "DependsOn" dependsOn=STRING "}"
		public Group getGroup() { return cGroup; }

		//"Stakeholder"
		public Keyword getStakeholderKeyword_0() { return cStakeholderKeyword_0; }

		//id=ID
		public Assignment getIdAssignment_1() { return cIdAssignment_1; }

		//ID
		public RuleCall getIdIDTerminalRuleCall_1_0() { return cIdIDTerminalRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//"Name"
		public Keyword getNameKeyword_3() { return cNameKeyword_3; }

		//name=STRING
		public Assignment getNameAssignment_4() { return cNameAssignment_4; }

		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_4_0() { return cNameSTRINGTerminalRuleCall_4_0; }

		//"Type"
		public Keyword getTypeKeyword_5() { return cTypeKeyword_5; }

		//type=STRING
		public Assignment getTypeAssignment_6() { return cTypeAssignment_6; }

		//STRING
		public RuleCall getTypeSTRINGTerminalRuleCall_6_0() { return cTypeSTRINGTerminalRuleCall_6_0; }

		//"Category"
		public Keyword getCategoryKeyword_7() { return cCategoryKeyword_7; }

		//cotegory=STRING
		public Assignment getCotegoryAssignment_8() { return cCotegoryAssignment_8; }

		//STRING
		public RuleCall getCotegorySTRINGTerminalRuleCall_8_0() { return cCotegorySTRINGTerminalRuleCall_8_0; }

		//"Description"
		public Keyword getDescriptionKeyword_9() { return cDescriptionKeyword_9; }

		//description=STRING
		public Assignment getDescriptionAssignment_10() { return cDescriptionAssignment_10; }

		//STRING
		public RuleCall getDescriptionSTRINGTerminalRuleCall_10_0() { return cDescriptionSTRINGTerminalRuleCall_10_0; }

		//"DependsOnType"
		public Keyword getDependsOnTypeKeyword_11() { return cDependsOnTypeKeyword_11; }

		//dependsOnType=STRING
		public Assignment getDependsOnTypeAssignment_12() { return cDependsOnTypeAssignment_12; }

		//STRING
		public RuleCall getDependsOnTypeSTRINGTerminalRuleCall_12_0() { return cDependsOnTypeSTRINGTerminalRuleCall_12_0; }

		//"DependsOn"
		public Keyword getDependsOnKeyword_13() { return cDependsOnKeyword_13; }

		//dependsOn=STRING
		public Assignment getDependsOnAssignment_14() { return cDependsOnAssignment_14; }

		//STRING
		public RuleCall getDependsOnSTRINGTerminalRuleCall_14_0() { return cDependsOnSTRINGTerminalRuleCall_14_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_15() { return cRightCurlyBracketKeyword_15; }
	}

	public class GoalElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Goal");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cGoalKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cIdAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cIdIDTerminalRuleCall_1_0 = (RuleCall)cIdAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cDescriptionKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cDescriptionAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cDescriptionSTRINGTerminalRuleCall_4_0 = (RuleCall)cDescriptionAssignment_4.eContents().get(0);
		private final Keyword cStakeholderKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cStakeholderAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final CrossReference cStakeholderStakeholderCrossReference_6_0 = (CrossReference)cStakeholderAssignment_6.eContents().get(0);
		private final RuleCall cStakeholderStakeholderIDTerminalRuleCall_6_0_1 = (RuleCall)cStakeholderStakeholderCrossReference_6_0.eContents().get(1);
		private final Keyword cPriorityKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cPriorityAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cPrioritySTRINGTerminalRuleCall_8_0 = (RuleCall)cPriorityAssignment_8.eContents().get(0);
		private final Keyword cDependsOnTypeKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cDependsOnTypeAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cDependsOnTypeSTRINGTerminalRuleCall_10_0 = (RuleCall)cDependsOnTypeAssignment_10.eContents().get(0);
		private final Keyword cDependsOnKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Assignment cDependsOnAssignment_12 = (Assignment)cGroup.eContents().get(12);
		private final RuleCall cDependsOnSTRINGTerminalRuleCall_12_0 = (RuleCall)cDependsOnAssignment_12.eContents().get(0);
		private final Keyword cComposedByTypeKeyword_13 = (Keyword)cGroup.eContents().get(13);
		private final Assignment cComposedByTypeAssignment_14 = (Assignment)cGroup.eContents().get(14);
		private final RuleCall cComposedByTypeSTRINGTerminalRuleCall_14_0 = (RuleCall)cComposedByTypeAssignment_14.eContents().get(0);
		private final Keyword cComposedByKeyword_15 = (Keyword)cGroup.eContents().get(15);
		private final Assignment cComposedByAssignment_16 = (Assignment)cGroup.eContents().get(16);
		private final RuleCall cComposedBySTRINGTerminalRuleCall_16_0 = (RuleCall)cComposedByAssignment_16.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_17 = (Keyword)cGroup.eContents().get(17);
		
		//Goal:
		//	"Goal" id=ID "{" "Description" description=STRING "Stakeholder" stakeholder=[Stakeholder] "Priority" priority=STRING
		//	"DependsOnType" dependsOnType=STRING "DependsOn" dependsOn=STRING "ComposedByType" composedByType=STRING "ComposedBy"
		//	composedBy=STRING "}";
		@Override public ParserRule getRule() { return rule; }

		//"Goal" id=ID "{" "Description" description=STRING "Stakeholder" stakeholder=[Stakeholder] "Priority" priority=STRING
		//"DependsOnType" dependsOnType=STRING "DependsOn" dependsOn=STRING "ComposedByType" composedByType=STRING "ComposedBy"
		//composedBy=STRING "}"
		public Group getGroup() { return cGroup; }

		//"Goal"
		public Keyword getGoalKeyword_0() { return cGoalKeyword_0; }

		//id=ID
		public Assignment getIdAssignment_1() { return cIdAssignment_1; }

		//ID
		public RuleCall getIdIDTerminalRuleCall_1_0() { return cIdIDTerminalRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//"Description"
		public Keyword getDescriptionKeyword_3() { return cDescriptionKeyword_3; }

		//description=STRING
		public Assignment getDescriptionAssignment_4() { return cDescriptionAssignment_4; }

		//STRING
		public RuleCall getDescriptionSTRINGTerminalRuleCall_4_0() { return cDescriptionSTRINGTerminalRuleCall_4_0; }

		//"Stakeholder"
		public Keyword getStakeholderKeyword_5() { return cStakeholderKeyword_5; }

		//stakeholder=[Stakeholder]
		public Assignment getStakeholderAssignment_6() { return cStakeholderAssignment_6; }

		//[Stakeholder]
		public CrossReference getStakeholderStakeholderCrossReference_6_0() { return cStakeholderStakeholderCrossReference_6_0; }

		//ID
		public RuleCall getStakeholderStakeholderIDTerminalRuleCall_6_0_1() { return cStakeholderStakeholderIDTerminalRuleCall_6_0_1; }

		//"Priority"
		public Keyword getPriorityKeyword_7() { return cPriorityKeyword_7; }

		//priority=STRING
		public Assignment getPriorityAssignment_8() { return cPriorityAssignment_8; }

		//STRING
		public RuleCall getPrioritySTRINGTerminalRuleCall_8_0() { return cPrioritySTRINGTerminalRuleCall_8_0; }

		//"DependsOnType"
		public Keyword getDependsOnTypeKeyword_9() { return cDependsOnTypeKeyword_9; }

		//dependsOnType=STRING
		public Assignment getDependsOnTypeAssignment_10() { return cDependsOnTypeAssignment_10; }

		//STRING
		public RuleCall getDependsOnTypeSTRINGTerminalRuleCall_10_0() { return cDependsOnTypeSTRINGTerminalRuleCall_10_0; }

		//"DependsOn"
		public Keyword getDependsOnKeyword_11() { return cDependsOnKeyword_11; }

		//dependsOn=STRING
		public Assignment getDependsOnAssignment_12() { return cDependsOnAssignment_12; }

		//STRING
		public RuleCall getDependsOnSTRINGTerminalRuleCall_12_0() { return cDependsOnSTRINGTerminalRuleCall_12_0; }

		//"ComposedByType"
		public Keyword getComposedByTypeKeyword_13() { return cComposedByTypeKeyword_13; }

		//composedByType=STRING
		public Assignment getComposedByTypeAssignment_14() { return cComposedByTypeAssignment_14; }

		//STRING
		public RuleCall getComposedByTypeSTRINGTerminalRuleCall_14_0() { return cComposedByTypeSTRINGTerminalRuleCall_14_0; }

		//"ComposedBy"
		public Keyword getComposedByKeyword_15() { return cComposedByKeyword_15; }

		//composedBy=STRING
		public Assignment getComposedByAssignment_16() { return cComposedByAssignment_16; }

		//STRING
		public RuleCall getComposedBySTRINGTerminalRuleCall_16_0() { return cComposedBySTRINGTerminalRuleCall_16_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_17() { return cRightCurlyBracketKeyword_17; }
	}
	
	
	private final ModelElements pModel;
	private final SystemElements pSystem;
	private final RefSystemElements pRefSystem;
	private final GlossaryElements pGlossary;
	private final StakeholderElements pStakeholder;
	private final GoalElements pGoal;
	
	private final Grammar grammar;

	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public RSLILGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pModel = new ModelElements();
		this.pSystem = new SystemElements();
		this.pRefSystem = new RefSystemElements();
		this.pGlossary = new GlossaryElements();
		this.pStakeholder = new StakeholderElements();
		this.pGoal = new GoalElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("rslingo.rslil.RSLIL".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Model: // Business Level
	//	systems+=System* glossaries+=Glossary* stakeholders+=Stakeholder* goals+=Goal*;
	public ModelElements getModelAccess() {
		return pModel;
	}
	
	public ParserRule getModelRule() {
		return getModelAccess().getRule();
	}

	//// TODO System Level
	//System:
	//	"System" id=ID "{" "Id" systemId=STRING "Name" name=STRING "Description" description=STRING ("DecomposedBy"
	//	refSystem=RefSystem)? ("PartOf" partOf=[System])? "}";
	public SystemElements getSystemAccess() {
		return pSystem;
	}
	
	public ParserRule getSystemRule() {
		return getSystemAccess().getRule();
	}

	//RefSystem:
	//	refSystem=[System] ("," refs+=[System])*;
	public RefSystemElements getRefSystemAccess() {
		return pRefSystem;
	}
	
	public ParserRule getRefSystemRule() {
		return getRefSystemAccess().getRule();
	}

	//Glossary:
	//	"Glossary" id=ID "{" "Name" name=STRING "Type" type=STRING "Acronym" acronym=STRING "Description" description=STRING
	//	"POS" pos=STRING "Synset" synset=STRING "TermRelationType" termRelationType=STRING "TermRelation" termRelation=STRING
	//	"}";
	public GlossaryElements getGlossaryAccess() {
		return pGlossary;
	}
	
	public ParserRule getGlossaryRule() {
		return getGlossaryAccess().getRule();
	}

	//Stakeholder:
	//	"Stakeholder" id=ID "{" "Name" name=STRING "Type" type=STRING "Category" cotegory=STRING "Description"
	//	description=STRING "DependsOnType" dependsOnType=STRING "DependsOn" dependsOn=STRING "}";
	public StakeholderElements getStakeholderAccess() {
		return pStakeholder;
	}
	
	public ParserRule getStakeholderRule() {
		return getStakeholderAccess().getRule();
	}

	//Goal:
	//	"Goal" id=ID "{" "Description" description=STRING "Stakeholder" stakeholder=[Stakeholder] "Priority" priority=STRING
	//	"DependsOnType" dependsOnType=STRING "DependsOn" dependsOn=STRING "ComposedByType" composedByType=STRING "ComposedBy"
	//	composedBy=STRING "}";
	public GoalElements getGoalAccess() {
		return pGoal;
	}
	
	public ParserRule getGoalRule() {
		return getGoalAccess().getRule();
	}

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" . / * 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' * / | !("\\" | "\""))* "\"" | "\'" ("\\" .
	//	/ * 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' * / | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
