/*
 * generated by Xtext
 */
package rslingo.rslil.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import rslingo.rslil.services.RSLILGrammarAccess;

public class RSLILParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private RSLILGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected rslingo.rslil.parser.antlr.internal.InternalRSLILParser createParser(XtextTokenStream stream) {
		return new rslingo.rslil.parser.antlr.internal.InternalRSLILParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public RSLILGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(RSLILGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
