/*
 * generated by Xtext
 */
package rslingo.rslil.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractRSLILValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(rslingo.rslil.rSLIL.RSLILPackage.eINSTANCE);
		return result;
	}
}
