/*
 * generated by Xtext
 */
package rslingo.rslil;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class RSLILRuntimeModule extends rslingo.rslil.AbstractRSLILRuntimeModule {

}
