/*
 * generated by Xtext
 */
package rslingo.rslil;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class RSLILUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return rslingo.rslil.ui.internal.RSLILActivator.getInstance().getInjector("rslingo.rslil.RSLIL");
	}
	
}
