/*
 * generated by Xtext
 */
package rslingo.rslil.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import rslingo.rslil.ui.internal.RSLILActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class RSLILExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return RSLILActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return RSLILActivator.getInstance().getInjector(RSLILActivator.RSLINGO_RSLIL_RSLIL);
	}
	
}
