/*
 * generated by Xtext
 */
package rslingo.rslil.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import rslingo.rslil.services.RSLILGrammarAccess;

public class RSLILParser extends AbstractContentAssistParser {
	
	@Inject
	private RSLILGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected rslingo.rslil.ui.contentassist.antlr.internal.InternalRSLILParser createParser() {
		rslingo.rslil.ui.contentassist.antlr.internal.InternalRSLILParser result = new rslingo.rslil.ui.contentassist.antlr.internal.InternalRSLILParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getGlossaryTermAccess().getPosAlternatives_9_1_0(), "rule__GlossaryTerm__PosAlternatives_9_1_0");
					put(grammarAccess.getTermTypeAccess().getTypeAlternatives_0(), "rule__TermType__TypeAlternatives_0");
					put(grammarAccess.getTermRelationAccess().getTypeAlternatives_0_0(), "rule__TermRelation__TypeAlternatives_0_0");
					put(grammarAccess.getStakeholderAccess().getTypeAlternatives_5_0(), "rule__Stakeholder__TypeAlternatives_5_0");
					put(grammarAccess.getStakeholderAccess().getCategoryAlternatives_7_0(), "rule__Stakeholder__CategoryAlternatives_7_0");
					put(grammarAccess.getGoalAccess().getPriorityAlternatives_8_0(), "rule__Goal__PriorityAlternatives_8_0");
					put(grammarAccess.getDependsOnGoalAccess().getTypeAlternatives_0_0(), "rule__DependsOnGoal__TypeAlternatives_0_0");
					put(grammarAccess.getComposedByAccess().getTypeAlternatives_1_0(), "rule__ComposedBy__TypeAlternatives_1_0");
					put(grammarAccess.getEntityAccess().getTypeAlternatives_6_1_0(), "rule__Entity__TypeAlternatives_6_1_0");
					put(grammarAccess.getAttributeAccess().getTypeAlternatives_7_0(), "rule__Attribute__TypeAlternatives_7_0");
					put(grammarAccess.getMultiplicityAccess().getValueAlternatives_0(), "rule__Multiplicity__ValueAlternatives_0");
					put(grammarAccess.getActorAccess().getTypeAlternatives_5_0(), "rule__Actor__TypeAlternatives_5_0");
					put(grammarAccess.getUseCaseAccess().getTypeAlternatives_5_0(), "rule__UseCase__TypeAlternatives_5_0");
					put(grammarAccess.getUseCaseAccess().getPriotityAlternatives_9_0(), "rule__UseCase__PriotityAlternatives_9_0");
					put(grammarAccess.getScenarioAccess().getTypeAlternatives_6_0(), "rule__Scenario__TypeAlternatives_6_0");
					put(grammarAccess.getScenarioAccess().getModeAlternatives_8_0(), "rule__Scenario__ModeAlternatives_8_0");
					put(grammarAccess.getStepAccess().getTypeAlternatives_5_0(), "rule__Step__TypeAlternatives_5_0");
					put(grammarAccess.getFRAccess().getTypeAlternatives_7_0(), "rule__FR__TypeAlternatives_7_0");
					put(grammarAccess.getFRAccess().getModalityAlternatives_9_0(), "rule__FR__ModalityAlternatives_9_0");
					put(grammarAccess.getFRAccess().getPriorityAlternatives_12_0(), "rule__FR__PriorityAlternatives_12_0");
					put(grammarAccess.getDependsOnFRAccess().getTypeAlternatives_0_0(), "rule__DependsOnFR__TypeAlternatives_0_0");
					put(grammarAccess.getNFRAccess().getTypeAlternatives_7_0(), "rule__NFR__TypeAlternatives_7_0");
					put(grammarAccess.getNFRAccess().getSubTypeAlternatives_8_1_0(), "rule__NFR__SubTypeAlternatives_8_1_0");
					put(grammarAccess.getNFRAccess().getMetricAlternatives_10_0(), "rule__NFR__MetricAlternatives_10_0");
					put(grammarAccess.getNFRAccess().getPriorityAlternatives_15_0(), "rule__NFR__PriorityAlternatives_15_0");
					put(grammarAccess.getDependsOnNFRAccess().getTypeAlternatives_0_0(), "rule__DependsOnNFR__TypeAlternatives_0_0");
					put(grammarAccess.getModelAccess().getGroup(), "rule__Model__Group__0");
					put(grammarAccess.getProjectAccess().getGroup(), "rule__Project__Group__0");
					put(grammarAccess.getProjectAccess().getGroup_3(), "rule__Project__Group_3__0");
					put(grammarAccess.getProjectAccess().getGroup_6(), "rule__Project__Group_6__0");
					put(grammarAccess.getSystemAccess().getGroup(), "rule__System__Group__0");
					put(grammarAccess.getSystemAccess().getGroup_3(), "rule__System__Group_3__0");
					put(grammarAccess.getSystemAccess().getGroup_6(), "rule__System__Group_6__0");
					put(grammarAccess.getRefSystemAccess().getGroup(), "rule__RefSystem__Group__0");
					put(grammarAccess.getRefSystemAccess().getGroup_1(), "rule__RefSystem__Group_1__0");
					put(grammarAccess.getGlossaryTermAccess().getGroup(), "rule__GlossaryTerm__Group__0");
					put(grammarAccess.getGlossaryTermAccess().getGroup_3(), "rule__GlossaryTerm__Group_3__0");
					put(grammarAccess.getGlossaryTermAccess().getGroup_6(), "rule__GlossaryTerm__Group_6__0");
					put(grammarAccess.getGlossaryTermAccess().getGroup_9(), "rule__GlossaryTerm__Group_9__0");
					put(grammarAccess.getGlossaryTermAccess().getGroup_10(), "rule__GlossaryTerm__Group_10__0");
					put(grammarAccess.getRefTermTypeAccess().getGroup(), "rule__RefTermType__Group__0");
					put(grammarAccess.getRefTermTypeAccess().getGroup_1(), "rule__RefTermType__Group_1__0");
					put(grammarAccess.getTermRelationAccess().getGroup(), "rule__TermRelation__Group__0");
					put(grammarAccess.getRefTermAccess().getGroup(), "rule__RefTerm__Group__0");
					put(grammarAccess.getRefTermAccess().getGroup_1(), "rule__RefTerm__Group_1__0");
					put(grammarAccess.getStakeholderAccess().getGroup(), "rule__Stakeholder__Group__0");
					put(grammarAccess.getStakeholderAccess().getGroup_3(), "rule__Stakeholder__Group_3__0");
					put(grammarAccess.getStakeholderAccess().getGroup_8(), "rule__Stakeholder__Group_8__0");
					put(grammarAccess.getStakeholderAccess().getGroup_9(), "rule__Stakeholder__Group_9__0");
					put(grammarAccess.getGoalAccess().getGroup(), "rule__Goal__Group__0");
					put(grammarAccess.getGoalAccess().getGroup_3(), "rule__Goal__Group_3__0");
					put(grammarAccess.getGoalAccess().getGroup_6(), "rule__Goal__Group_6__0");
					put(grammarAccess.getDependsOnGoalAccess().getGroup(), "rule__DependsOnGoal__Group__0");
					put(grammarAccess.getComposedByAccess().getGroup(), "rule__ComposedBy__Group__0");
					put(grammarAccess.getRefGoalAccess().getGroup(), "rule__RefGoal__Group__0");
					put(grammarAccess.getRefGoalAccess().getGroup_1(), "rule__RefGoal__Group_1__0");
					put(grammarAccess.getEntityAccess().getGroup(), "rule__Entity__Group__0");
					put(grammarAccess.getEntityAccess().getGroup_3(), "rule__Entity__Group_3__0");
					put(grammarAccess.getEntityAccess().getGroup_6(), "rule__Entity__Group_6__0");
					put(grammarAccess.getAttributeAccess().getGroup(), "rule__Attribute__Group__0");
					put(grammarAccess.getAttributeAccess().getGroup_3(), "rule__Attribute__Group_3__0");
					put(grammarAccess.getFieldAccess().getGroup(), "rule__Field__Group__0");
					put(grammarAccess.getFieldAccess().getGroup_6(), "rule__Field__Group_6__0");
					put(grammarAccess.getReferenceAccess().getGroup(), "rule__Reference__Group__0");
					put(grammarAccess.getRefAttributeAccess().getGroup(), "rule__RefAttribute__Group__0");
					put(grammarAccess.getRefAttributeAccess().getGroup_1(), "rule__RefAttribute__Group_1__0");
					put(grammarAccess.getActorAccess().getGroup(), "rule__Actor__Group__0");
					put(grammarAccess.getActorAccess().getGroup_3(), "rule__Actor__Group_3__0");
					put(grammarAccess.getActorAccess().getGroup_8(), "rule__Actor__Group_8__0");
					put(grammarAccess.getActorAccess().getGroup_9(), "rule__Actor__Group_9__0");
					put(grammarAccess.getUseCaseAccess().getGroup(), "rule__UseCase__Group__0");
					put(grammarAccess.getUseCaseAccess().getGroup_3(), "rule__UseCase__Group_3__0");
					put(grammarAccess.getUseCaseAccess().getGroup_11(), "rule__UseCase__Group_11__0");
					put(grammarAccess.getUseCaseAccess().getGroup_12(), "rule__UseCase__Group_12__0");
					put(grammarAccess.getUseCaseAccess().getGroup_15(), "rule__UseCase__Group_15__0");
					put(grammarAccess.getUseCaseAccess().getGroup_16(), "rule__UseCase__Group_16__0");
					put(grammarAccess.getUseCaseAccess().getGroup_17(), "rule__UseCase__Group_17__0");
					put(grammarAccess.getUseCaseAccess().getGroup_18(), "rule__UseCase__Group_18__0");
					put(grammarAccess.getUseCaseAccess().getGroup_19(), "rule__UseCase__Group_19__0");
					put(grammarAccess.getRefFRAccess().getGroup(), "rule__RefFR__Group__0");
					put(grammarAccess.getRefFRAccess().getGroup_1(), "rule__RefFR__Group_1__0");
					put(grammarAccess.getRefActorAccess().getGroup(), "rule__RefActor__Group__0");
					put(grammarAccess.getRefActorAccess().getGroup_1(), "rule__RefActor__Group_1__0");
					put(grammarAccess.getRefUCAccess().getGroup(), "rule__RefUC__Group__0");
					put(grammarAccess.getRefUCAccess().getGroup_1(), "rule__RefUC__Group_1__0");
					put(grammarAccess.getExtensionPointAccess().getGroup(), "rule__ExtensionPoint__Group__0");
					put(grammarAccess.getExtensionPointAccess().getGroup_2(), "rule__ExtensionPoint__Group_2__0");
					put(grammarAccess.getScenarioAccess().getGroup(), "rule__Scenario__Group__0");
					put(grammarAccess.getScenarioAccess().getGroup_3(), "rule__Scenario__Group_3__0");
					put(grammarAccess.getScenarioAccess().getGroup_4(), "rule__Scenario__Group_4__0");
					put(grammarAccess.getStepAccess().getGroup(), "rule__Step__Group__0");
					put(grammarAccess.getStepAccess().getGroup_3(), "rule__Step__Group_3__0");
					put(grammarAccess.getStepAccess().getGroup_8(), "rule__Step__Group_8__0");
					put(grammarAccess.getStepAccess().getGroup_9(), "rule__Step__Group_9__0");
					put(grammarAccess.getStepAccess().getGroup_10(), "rule__Step__Group_10__0");
					put(grammarAccess.getStepAccess().getGroup_11(), "rule__Step__Group_11__0");
					put(grammarAccess.getFRAccess().getGroup(), "rule__FR__Group__0");
					put(grammarAccess.getFRAccess().getGroup_3(), "rule__FR__Group_3__0");
					put(grammarAccess.getFRAccess().getGroup_10(), "rule__FR__Group_10__0");
					put(grammarAccess.getFRAccess().getGroup_14(), "rule__FR__Group_14__0");
					put(grammarAccess.getDependsOnFRAccess().getGroup(), "rule__DependsOnFR__Group__0");
					put(grammarAccess.getNFRAccess().getGroup(), "rule__NFR__Group__0");
					put(grammarAccess.getNFRAccess().getGroup_3(), "rule__NFR__Group_3__0");
					put(grammarAccess.getNFRAccess().getGroup_8(), "rule__NFR__Group_8__0");
					put(grammarAccess.getNFRAccess().getGroup_13(), "rule__NFR__Group_13__0");
					put(grammarAccess.getNFRAccess().getGroup_17(), "rule__NFR__Group_17__0");
					put(grammarAccess.getDependsOnNFRAccess().getGroup(), "rule__DependsOnNFR__Group__0");
					put(grammarAccess.getRefNFRAccess().getGroup(), "rule__RefNFR__Group__0");
					put(grammarAccess.getRefNFRAccess().getGroup_1(), "rule__RefNFR__Group_1__0");
					put(grammarAccess.getModelAccess().getProjectAssignment_0(), "rule__Model__ProjectAssignment_0");
					put(grammarAccess.getModelAccess().getSystemsAssignment_1(), "rule__Model__SystemsAssignment_1");
					put(grammarAccess.getModelAccess().getGlossaryTermsAssignment_2(), "rule__Model__GlossaryTermsAssignment_2");
					put(grammarAccess.getModelAccess().getStakeholdersAssignment_3(), "rule__Model__StakeholdersAssignment_3");
					put(grammarAccess.getModelAccess().getGoalsAssignment_4(), "rule__Model__GoalsAssignment_4");
					put(grammarAccess.getModelAccess().getEntitiesAssignment_5(), "rule__Model__EntitiesAssignment_5");
					put(grammarAccess.getModelAccess().getActorsAssignment_6(), "rule__Model__ActorsAssignment_6");
					put(grammarAccess.getModelAccess().getUseCasesAssignment_7(), "rule__Model__UseCasesAssignment_7");
					put(grammarAccess.getModelAccess().getFrsAssignment_8(), "rule__Model__FrsAssignment_8");
					put(grammarAccess.getModelAccess().getNfrsAssignment_9(), "rule__Model__NfrsAssignment_9");
					put(grammarAccess.getProjectAccess().getNameAssignment_1(), "rule__Project__NameAssignment_1");
					put(grammarAccess.getProjectAccess().getNameAliasAssignment_3_1(), "rule__Project__NameAliasAssignment_3_1");
					put(grammarAccess.getProjectAccess().getDescriptionAssignment_5(), "rule__Project__DescriptionAssignment_5");
					put(grammarAccess.getProjectAccess().getRefSystemAssignment_6_1(), "rule__Project__RefSystemAssignment_6_1");
					put(grammarAccess.getSystemAccess().getNameAssignment_1(), "rule__System__NameAssignment_1");
					put(grammarAccess.getSystemAccess().getNameAliasAssignment_3_1(), "rule__System__NameAliasAssignment_3_1");
					put(grammarAccess.getSystemAccess().getDescriptionAssignment_5(), "rule__System__DescriptionAssignment_5");
					put(grammarAccess.getSystemAccess().getPartOfAssignment_6_1(), "rule__System__PartOfAssignment_6_1");
					put(grammarAccess.getRefSystemAccess().getRefSystemAssignment_0(), "rule__RefSystem__RefSystemAssignment_0");
					put(grammarAccess.getRefSystemAccess().getRefsAssignment_1_1(), "rule__RefSystem__RefsAssignment_1_1");
					put(grammarAccess.getGlossaryTermAccess().getNameAssignment_1(), "rule__GlossaryTerm__NameAssignment_1");
					put(grammarAccess.getGlossaryTermAccess().getNameAliasAssignment_3_1(), "rule__GlossaryTerm__NameAliasAssignment_3_1");
					put(grammarAccess.getGlossaryTermAccess().getTypeAssignment_5(), "rule__GlossaryTerm__TypeAssignment_5");
					put(grammarAccess.getGlossaryTermAccess().getAcronymAssignment_6_1(), "rule__GlossaryTerm__AcronymAssignment_6_1");
					put(grammarAccess.getGlossaryTermAccess().getDescriptionAssignment_8(), "rule__GlossaryTerm__DescriptionAssignment_8");
					put(grammarAccess.getGlossaryTermAccess().getPosAssignment_9_1(), "rule__GlossaryTerm__PosAssignment_9_1");
					put(grammarAccess.getGlossaryTermAccess().getSynsetAssignment_10_1(), "rule__GlossaryTerm__SynsetAssignment_10_1");
					put(grammarAccess.getGlossaryTermAccess().getTermRelationAssignment_11(), "rule__GlossaryTerm__TermRelationAssignment_11");
					put(grammarAccess.getRefTermTypeAccess().getRefTypeAssignment_0(), "rule__RefTermType__RefTypeAssignment_0");
					put(grammarAccess.getRefTermTypeAccess().getRefsAssignment_1_1(), "rule__RefTermType__RefsAssignment_1_1");
					put(grammarAccess.getTermTypeAccess().getTypeAssignment(), "rule__TermType__TypeAssignment");
					put(grammarAccess.getTermRelationAccess().getTypeAssignment_0(), "rule__TermRelation__TypeAssignment_0");
					put(grammarAccess.getTermRelationAccess().getRefTermAssignment_1(), "rule__TermRelation__RefTermAssignment_1");
					put(grammarAccess.getRefTermAccess().getRefTermAssignment_0(), "rule__RefTerm__RefTermAssignment_0");
					put(grammarAccess.getRefTermAccess().getRefsAssignment_1_1(), "rule__RefTerm__RefsAssignment_1_1");
					put(grammarAccess.getStakeholderAccess().getNameAssignment_1(), "rule__Stakeholder__NameAssignment_1");
					put(grammarAccess.getStakeholderAccess().getNameAliasAssignment_3_1(), "rule__Stakeholder__NameAliasAssignment_3_1");
					put(grammarAccess.getStakeholderAccess().getTypeAssignment_5(), "rule__Stakeholder__TypeAssignment_5");
					put(grammarAccess.getStakeholderAccess().getCategoryAssignment_7(), "rule__Stakeholder__CategoryAssignment_7");
					put(grammarAccess.getStakeholderAccess().getDescriptionAssignment_8_1(), "rule__Stakeholder__DescriptionAssignment_8_1");
					put(grammarAccess.getStakeholderAccess().getPartOfAssignment_9_1(), "rule__Stakeholder__PartOfAssignment_9_1");
					put(grammarAccess.getGoalAccess().getNameAssignment_1(), "rule__Goal__NameAssignment_1");
					put(grammarAccess.getGoalAccess().getNameAliasAssignment_3_1(), "rule__Goal__NameAliasAssignment_3_1");
					put(grammarAccess.getGoalAccess().getDescriptionAssignment_5(), "rule__Goal__DescriptionAssignment_5");
					put(grammarAccess.getGoalAccess().getStakeholderAssignment_6_1(), "rule__Goal__StakeholderAssignment_6_1");
					put(grammarAccess.getGoalAccess().getPriorityAssignment_8(), "rule__Goal__PriorityAssignment_8");
					put(grammarAccess.getGoalAccess().getDependsOnAssignment_9(), "rule__Goal__DependsOnAssignment_9");
					put(grammarAccess.getGoalAccess().getComposedByAssignment_10(), "rule__Goal__ComposedByAssignment_10");
					put(grammarAccess.getDependsOnGoalAccess().getTypeAssignment_0(), "rule__DependsOnGoal__TypeAssignment_0");
					put(grammarAccess.getDependsOnGoalAccess().getRefGoalAssignment_1(), "rule__DependsOnGoal__RefGoalAssignment_1");
					put(grammarAccess.getComposedByAccess().getTypeAssignment_1(), "rule__ComposedBy__TypeAssignment_1");
					put(grammarAccess.getComposedByAccess().getRefGoalAssignment_2(), "rule__ComposedBy__RefGoalAssignment_2");
					put(grammarAccess.getRefGoalAccess().getRefGoalAssignment_0(), "rule__RefGoal__RefGoalAssignment_0");
					put(grammarAccess.getRefGoalAccess().getRefsAssignment_1_1(), "rule__RefGoal__RefsAssignment_1_1");
					put(grammarAccess.getEntityAccess().getNameAssignment_1(), "rule__Entity__NameAssignment_1");
					put(grammarAccess.getEntityAccess().getNameAliasAssignment_3_1(), "rule__Entity__NameAliasAssignment_3_1");
					put(grammarAccess.getEntityAccess().getDescriptionAssignment_5(), "rule__Entity__DescriptionAssignment_5");
					put(grammarAccess.getEntityAccess().getTypeAssignment_6_1(), "rule__Entity__TypeAssignment_6_1");
					put(grammarAccess.getEntityAccess().getAttributesAssignment_7(), "rule__Entity__AttributesAssignment_7");
					put(grammarAccess.getEntityAccess().getReferenceAssignment_8(), "rule__Entity__ReferenceAssignment_8");
					put(grammarAccess.getAttributeAccess().getNameAssignment_1(), "rule__Attribute__NameAssignment_1");
					put(grammarAccess.getAttributeAccess().getNameAliasAssignment_3_1(), "rule__Attribute__NameAliasAssignment_3_1");
					put(grammarAccess.getAttributeAccess().getDescriptionAssignment_5(), "rule__Attribute__DescriptionAssignment_5");
					put(grammarAccess.getAttributeAccess().getTypeAssignment_7(), "rule__Attribute__TypeAssignment_7");
					put(grammarAccess.getAttributeAccess().getFieldAssignment_8(), "rule__Attribute__FieldAssignment_8");
					put(grammarAccess.getFieldAccess().getSizeAssignment_3(), "rule__Field__SizeAssignment_3");
					put(grammarAccess.getFieldAccess().getMultiplicityAssignment_5(), "rule__Field__MultiplicityAssignment_5");
					put(grammarAccess.getFieldAccess().getDefaultValueAssignment_6_1(), "rule__Field__DefaultValueAssignment_6_1");
					put(grammarAccess.getMultiplicityAccess().getValueAssignment(), "rule__Multiplicity__ValueAssignment");
					put(grammarAccess.getReferenceAccess().getEntityAssignment_1(), "rule__Reference__EntityAssignment_1");
					put(grammarAccess.getReferenceAccess().getRefToAssignment_3(), "rule__Reference__RefToAssignment_3");
					put(grammarAccess.getReferenceAccess().getMultiplicityAssignment_6(), "rule__Reference__MultiplicityAssignment_6");
					put(grammarAccess.getRefAttributeAccess().getRefAttrAssignment_0(), "rule__RefAttribute__RefAttrAssignment_0");
					put(grammarAccess.getRefAttributeAccess().getRefsAssignment_1_1(), "rule__RefAttribute__RefsAssignment_1_1");
					put(grammarAccess.getActorAccess().getNameAssignment_1(), "rule__Actor__NameAssignment_1");
					put(grammarAccess.getActorAccess().getNameAliasAssignment_3_1(), "rule__Actor__NameAliasAssignment_3_1");
					put(grammarAccess.getActorAccess().getTypeAssignment_5(), "rule__Actor__TypeAssignment_5");
					put(grammarAccess.getActorAccess().getDescriptionAssignment_7(), "rule__Actor__DescriptionAssignment_7");
					put(grammarAccess.getActorAccess().getStakeholderAssignment_8_1(), "rule__Actor__StakeholderAssignment_8_1");
					put(grammarAccess.getActorAccess().getActorAssignment_9_1(), "rule__Actor__ActorAssignment_9_1");
					put(grammarAccess.getUseCaseAccess().getNameAssignment_1(), "rule__UseCase__NameAssignment_1");
					put(grammarAccess.getUseCaseAccess().getNameAliasAssignment_3_1(), "rule__UseCase__NameAliasAssignment_3_1");
					put(grammarAccess.getUseCaseAccess().getTypeAssignment_5(), "rule__UseCase__TypeAssignment_5");
					put(grammarAccess.getUseCaseAccess().getDescriptionAssignment_7(), "rule__UseCase__DescriptionAssignment_7");
					put(grammarAccess.getUseCaseAccess().getPriotityAssignment_9(), "rule__UseCase__PriotityAssignment_9");
					put(grammarAccess.getUseCaseAccess().getExtensionnPointsAssignment_10(), "rule__UseCase__ExtensionnPointsAssignment_10");
					put(grammarAccess.getUseCaseAccess().getGoalsAssignment_11_1(), "rule__UseCase__GoalsAssignment_11_1");
					put(grammarAccess.getUseCaseAccess().getFrsAssignment_12_1(), "rule__UseCase__FrsAssignment_12_1");
					put(grammarAccess.getUseCaseAccess().getActorInitiatesAssignment_14(), "rule__UseCase__ActorInitiatesAssignment_14");
					put(grammarAccess.getUseCaseAccess().getActorsAssignment_15_1(), "rule__UseCase__ActorsAssignment_15_1");
					put(grammarAccess.getUseCaseAccess().getPreConditionsAssignment_16_1(), "rule__UseCase__PreConditionsAssignment_16_1");
					put(grammarAccess.getUseCaseAccess().getPostConditionsAssignment_17_1(), "rule__UseCase__PostConditionsAssignment_17_1");
					put(grammarAccess.getUseCaseAccess().getIncludesAssignment_18_1(), "rule__UseCase__IncludesAssignment_18_1");
					put(grammarAccess.getUseCaseAccess().getExtendsAssignment_19_1(), "rule__UseCase__ExtendsAssignment_19_1");
					put(grammarAccess.getUseCaseAccess().getExtPointAssignment_19_3(), "rule__UseCase__ExtPointAssignment_19_3");
					put(grammarAccess.getUseCaseAccess().getScenariosAssignment_20(), "rule__UseCase__ScenariosAssignment_20");
					put(grammarAccess.getRefFRAccess().getRefFRAssignment_0(), "rule__RefFR__RefFRAssignment_0");
					put(grammarAccess.getRefFRAccess().getRefsAssignment_1_1(), "rule__RefFR__RefsAssignment_1_1");
					put(grammarAccess.getRefActorAccess().getRefActorAssignment_0(), "rule__RefActor__RefActorAssignment_0");
					put(grammarAccess.getRefActorAccess().getRefsAssignment_1_1(), "rule__RefActor__RefsAssignment_1_1");
					put(grammarAccess.getRefUCAccess().getRefUCAssignment_0(), "rule__RefUC__RefUCAssignment_0");
					put(grammarAccess.getRefUCAccess().getRefsAssignment_1_1(), "rule__RefUC__RefsAssignment_1_1");
					put(grammarAccess.getExtensionPointAccess().getNameAssignment_1(), "rule__ExtensionPoint__NameAssignment_1");
					put(grammarAccess.getExtensionPointAccess().getDescriptionAssignment_2_1(), "rule__ExtensionPoint__DescriptionAssignment_2_1");
					put(grammarAccess.getScenarioAccess().getNameAssignment_1(), "rule__Scenario__NameAssignment_1");
					put(grammarAccess.getScenarioAccess().getNameAliasAssignment_3_1(), "rule__Scenario__NameAliasAssignment_3_1");
					put(grammarAccess.getScenarioAccess().getDescriptionAssignment_4_1(), "rule__Scenario__DescriptionAssignment_4_1");
					put(grammarAccess.getScenarioAccess().getTypeAssignment_6(), "rule__Scenario__TypeAssignment_6");
					put(grammarAccess.getScenarioAccess().getModeAssignment_8(), "rule__Scenario__ModeAssignment_8");
					put(grammarAccess.getScenarioAccess().getStepsAssignment_9(), "rule__Scenario__StepsAssignment_9");
					put(grammarAccess.getStepAccess().getNameAssignment_1(), "rule__Step__NameAssignment_1");
					put(grammarAccess.getStepAccess().getNameAliasAssignment_3_1(), "rule__Step__NameAliasAssignment_3_1");
					put(grammarAccess.getStepAccess().getTypeAssignment_5(), "rule__Step__TypeAssignment_5");
					put(grammarAccess.getStepAccess().getDescriptionAssignment_7(), "rule__Step__DescriptionAssignment_7");
					put(grammarAccess.getStepAccess().getActorAssignment_8_1(), "rule__Step__ActorAssignment_8_1");
					put(grammarAccess.getStepAccess().getPreConditionsAssignment_9_1(), "rule__Step__PreConditionsAssignment_9_1");
					put(grammarAccess.getStepAccess().getPostConditionsAssignment_10_1(), "rule__Step__PostConditionsAssignment_10_1");
					put(grammarAccess.getStepAccess().getNextAssignment_11_1(), "rule__Step__NextAssignment_11_1");
					put(grammarAccess.getFRAccess().getNameAssignment_1(), "rule__FR__NameAssignment_1");
					put(grammarAccess.getFRAccess().getNameAliasAssignment_3_1(), "rule__FR__NameAliasAssignment_3_1");
					put(grammarAccess.getFRAccess().getDescriptionAssignment_5(), "rule__FR__DescriptionAssignment_5");
					put(grammarAccess.getFRAccess().getTypeAssignment_7(), "rule__FR__TypeAssignment_7");
					put(grammarAccess.getFRAccess().getModalityAssignment_9(), "rule__FR__ModalityAssignment_9");
					put(grammarAccess.getFRAccess().getStakeholderAssignment_10_1(), "rule__FR__StakeholderAssignment_10_1");
					put(grammarAccess.getFRAccess().getPriorityAssignment_12(), "rule__FR__PriorityAssignment_12");
					put(grammarAccess.getFRAccess().getDependsAssignment_13(), "rule__FR__DependsAssignment_13");
					put(grammarAccess.getFRAccess().getPartOfAssignment_14_1(), "rule__FR__PartOfAssignment_14_1");
					put(grammarAccess.getDependsOnFRAccess().getTypeAssignment_0(), "rule__DependsOnFR__TypeAssignment_0");
					put(grammarAccess.getDependsOnFRAccess().getRefFrAssignment_1(), "rule__DependsOnFR__RefFrAssignment_1");
					put(grammarAccess.getNFRAccess().getNameAssignment_1(), "rule__NFR__NameAssignment_1");
					put(grammarAccess.getNFRAccess().getNameAliasAssignment_3_1(), "rule__NFR__NameAliasAssignment_3_1");
					put(grammarAccess.getNFRAccess().getDescriptionAssignment_5(), "rule__NFR__DescriptionAssignment_5");
					put(grammarAccess.getNFRAccess().getTypeAssignment_7(), "rule__NFR__TypeAssignment_7");
					put(grammarAccess.getNFRAccess().getSubTypeAssignment_8_1(), "rule__NFR__SubTypeAssignment_8_1");
					put(grammarAccess.getNFRAccess().getMetricAssignment_10(), "rule__NFR__MetricAssignment_10");
					put(grammarAccess.getNFRAccess().getValueAssignment_12(), "rule__NFR__ValueAssignment_12");
					put(grammarAccess.getNFRAccess().getStakeholderAssignment_13_1(), "rule__NFR__StakeholderAssignment_13_1");
					put(grammarAccess.getNFRAccess().getPriorityAssignment_15(), "rule__NFR__PriorityAssignment_15");
					put(grammarAccess.getNFRAccess().getDependsAssignment_16(), "rule__NFR__DependsAssignment_16");
					put(grammarAccess.getNFRAccess().getPartOfAssignment_17_1(), "rule__NFR__PartOfAssignment_17_1");
					put(grammarAccess.getDependsOnNFRAccess().getTypeAssignment_0(), "rule__DependsOnNFR__TypeAssignment_0");
					put(grammarAccess.getDependsOnNFRAccess().getRefFrAssignment_1(), "rule__DependsOnNFR__RefFrAssignment_1");
					put(grammarAccess.getRefNFRAccess().getRefNFRAssignment_0(), "rule__RefNFR__RefNFRAssignment_0");
					put(grammarAccess.getRefNFRAccess().getRefsAssignment_1_1(), "rule__RefNFR__RefsAssignment_1_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			rslingo.rslil.ui.contentassist.antlr.internal.InternalRSLILParser typedParser = (rslingo.rslil.ui.contentassist.antlr.internal.InternalRSLILParser) parser;
			typedParser.entryRuleModel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public RSLILGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(RSLILGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
