/*
 * generated by Xtext
 */
package rslingo.rslil.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import rslingo.rslil.services.RSLILGrammarAccess;

public class RSLILParser extends AbstractContentAssistParser {
	
	@Inject
	private RSLILGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected rslingo.rslil.ui.contentassist.antlr.internal.InternalRSLILParser createParser() {
		rslingo.rslil.ui.contentassist.antlr.internal.InternalRSLILParser result = new rslingo.rslil.ui.contentassist.antlr.internal.InternalRSLILParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getGlossaryAccess().getPosAlternatives_11_1_0(), "rule__Glossary__PosAlternatives_11_1_0");
					put(grammarAccess.getGlossaryTypeAccess().getTypeAlternatives_0(), "rule__GlossaryType__TypeAlternatives_0");
					put(grammarAccess.getTermRelationAccess().getTypeAlternatives_1_0(), "rule__TermRelation__TypeAlternatives_1_0");
					put(grammarAccess.getStakeholderAccess().getTypeAlternatives_6_0(), "rule__Stakeholder__TypeAlternatives_6_0");
					put(grammarAccess.getStakeholderAccess().getCategoryAlternatives_8_0(), "rule__Stakeholder__CategoryAlternatives_8_0");
					put(grammarAccess.getGoalAccess().getPriorityAlternatives_8_0(), "rule__Goal__PriorityAlternatives_8_0");
					put(grammarAccess.getDependsOnGoalAccess().getTypeAlternatives_0_0(), "rule__DependsOnGoal__TypeAlternatives_0_0");
					put(grammarAccess.getComposedByAccess().getTypeAlternatives_1_0(), "rule__ComposedBy__TypeAlternatives_1_0");
					put(grammarAccess.getAttributeAccess().getTypeAlternatives_7_0(), "rule__Attribute__TypeAlternatives_7_0");
					put(grammarAccess.getFieldAccess().getMultiplicityAlternatives_5_0(), "rule__Field__MultiplicityAlternatives_5_0");
					put(grammarAccess.getReferenceAccess().getMultiplicityAlternatives_3_0(), "rule__Reference__MultiplicityAlternatives_3_0");
					put(grammarAccess.getActorAccess().getTypeAlternatives_6_0(), "rule__Actor__TypeAlternatives_6_0");
					put(grammarAccess.getDependsOnActorAccess().getTypeAlternatives_0_0(), "rule__DependsOnActor__TypeAlternatives_0_0");
					put(grammarAccess.getModelAccess().getGroup(), "rule__Model__Group__0");
					put(grammarAccess.getProjectAccess().getGroup(), "rule__Project__Group__0");
					put(grammarAccess.getProjectAccess().getGroup_7(), "rule__Project__Group_7__0");
					put(grammarAccess.getSystemAccess().getGroup(), "rule__System__Group__0");
					put(grammarAccess.getSystemAccess().getGroup_7(), "rule__System__Group_7__0");
					put(grammarAccess.getRefSystemAccess().getGroup(), "rule__RefSystem__Group__0");
					put(grammarAccess.getRefSystemAccess().getGroup_1(), "rule__RefSystem__Group_1__0");
					put(grammarAccess.getGlossaryAccess().getGroup(), "rule__Glossary__Group__0");
					put(grammarAccess.getGlossaryAccess().getGroup_11(), "rule__Glossary__Group_11__0");
					put(grammarAccess.getGlossaryAccess().getGroup_12(), "rule__Glossary__Group_12__0");
					put(grammarAccess.getRefGlossaryTypeAccess().getGroup(), "rule__RefGlossaryType__Group__0");
					put(grammarAccess.getRefGlossaryTypeAccess().getGroup_1(), "rule__RefGlossaryType__Group_1__0");
					put(grammarAccess.getTermRelationAccess().getGroup(), "rule__TermRelation__Group__0");
					put(grammarAccess.getTermAccess().getGroup(), "rule__Term__Group__0");
					put(grammarAccess.getTermAccess().getGroup_1(), "rule__Term__Group_1__0");
					put(grammarAccess.getStakeholderAccess().getGroup(), "rule__Stakeholder__Group__0");
					put(grammarAccess.getStakeholderAccess().getGroup_9(), "rule__Stakeholder__Group_9__0");
					put(grammarAccess.getStakeholderAccess().getGroup_10(), "rule__Stakeholder__Group_10__0");
					put(grammarAccess.getGoalAccess().getGroup(), "rule__Goal__Group__0");
					put(grammarAccess.getDependsOnGoalAccess().getGroup(), "rule__DependsOnGoal__Group__0");
					put(grammarAccess.getComposedByAccess().getGroup(), "rule__ComposedBy__Group__0");
					put(grammarAccess.getEntityAccess().getGroup(), "rule__Entity__Group__0");
					put(grammarAccess.getAttributeAccess().getGroup(), "rule__Attribute__Group__0");
					put(grammarAccess.getFieldAccess().getGroup(), "rule__Field__Group__0");
					put(grammarAccess.getReferenceAccess().getGroup(), "rule__Reference__Group__0");
					put(grammarAccess.getRefAttributeAccess().getGroup(), "rule__RefAttribute__Group__0");
					put(grammarAccess.getRefAttributeAccess().getGroup_1(), "rule__RefAttribute__Group_1__0");
					put(grammarAccess.getActorAccess().getGroup(), "rule__Actor__Group__0");
					put(grammarAccess.getActorAccess().getGroup_9(), "rule__Actor__Group_9__0");
					put(grammarAccess.getDependsOnActorAccess().getGroup(), "rule__DependsOnActor__Group__0");
					put(grammarAccess.getUseCaseAccess().getGroup(), "rule__UseCase__Group__0");
					put(grammarAccess.getFRAccess().getGroup(), "rule__FR__Group__0");
					put(grammarAccess.getNFRAccess().getGroup(), "rule__NFR__Group__0");
					put(grammarAccess.getRefGoalAccess().getGroup(), "rule__RefGoal__Group__0");
					put(grammarAccess.getRefGoalAccess().getGroup_1(), "rule__RefGoal__Group_1__0");
					put(grammarAccess.getRefFRAccess().getGroup(), "rule__RefFR__Group__0");
					put(grammarAccess.getRefFRAccess().getGroup_1(), "rule__RefFR__Group_1__0");
					put(grammarAccess.getRefUCAccess().getGroup(), "rule__RefUC__Group__0");
					put(grammarAccess.getRefUCAccess().getGroup_1(), "rule__RefUC__Group_1__0");
					put(grammarAccess.getModelAccess().getProjectAssignment_0(), "rule__Model__ProjectAssignment_0");
					put(grammarAccess.getModelAccess().getSystemsAssignment_1(), "rule__Model__SystemsAssignment_1");
					put(grammarAccess.getModelAccess().getGlossariesAssignment_2(), "rule__Model__GlossariesAssignment_2");
					put(grammarAccess.getModelAccess().getStakeholdersAssignment_3(), "rule__Model__StakeholdersAssignment_3");
					put(grammarAccess.getModelAccess().getGoalsAssignment_4(), "rule__Model__GoalsAssignment_4");
					put(grammarAccess.getModelAccess().getEntitiesAssignment_5(), "rule__Model__EntitiesAssignment_5");
					put(grammarAccess.getModelAccess().getActorsAssignment_6(), "rule__Model__ActorsAssignment_6");
					put(grammarAccess.getModelAccess().getUseCasesAssignment_7(), "rule__Model__UseCasesAssignment_7");
					put(grammarAccess.getModelAccess().getFrsAssignment_8(), "rule__Model__FrsAssignment_8");
					put(grammarAccess.getModelAccess().getNfrsAssignment_9(), "rule__Model__NfrsAssignment_9");
					put(grammarAccess.getProjectAccess().getIdAssignment_1(), "rule__Project__IdAssignment_1");
					put(grammarAccess.getProjectAccess().getNameAssignment_4(), "rule__Project__NameAssignment_4");
					put(grammarAccess.getProjectAccess().getDescriptionAssignment_6(), "rule__Project__DescriptionAssignment_6");
					put(grammarAccess.getProjectAccess().getRefSystemAssignment_7_1(), "rule__Project__RefSystemAssignment_7_1");
					put(grammarAccess.getSystemAccess().getIdAssignment_1(), "rule__System__IdAssignment_1");
					put(grammarAccess.getSystemAccess().getNameAssignment_4(), "rule__System__NameAssignment_4");
					put(grammarAccess.getSystemAccess().getDescriptionAssignment_6(), "rule__System__DescriptionAssignment_6");
					put(grammarAccess.getSystemAccess().getPartOfAssignment_7_1(), "rule__System__PartOfAssignment_7_1");
					put(grammarAccess.getRefSystemAccess().getRefSystemAssignment_0(), "rule__RefSystem__RefSystemAssignment_0");
					put(grammarAccess.getRefSystemAccess().getRefsAssignment_1_1(), "rule__RefSystem__RefsAssignment_1_1");
					put(grammarAccess.getGlossaryAccess().getIdAssignment_1(), "rule__Glossary__IdAssignment_1");
					put(grammarAccess.getGlossaryAccess().getNameAssignment_4(), "rule__Glossary__NameAssignment_4");
					put(grammarAccess.getGlossaryAccess().getTypeAssignment_6(), "rule__Glossary__TypeAssignment_6");
					put(grammarAccess.getGlossaryAccess().getAcronymAssignment_8(), "rule__Glossary__AcronymAssignment_8");
					put(grammarAccess.getGlossaryAccess().getDescriptionAssignment_10(), "rule__Glossary__DescriptionAssignment_10");
					put(grammarAccess.getGlossaryAccess().getPosAssignment_11_1(), "rule__Glossary__PosAssignment_11_1");
					put(grammarAccess.getGlossaryAccess().getSynsetAssignment_12_1(), "rule__Glossary__SynsetAssignment_12_1");
					put(grammarAccess.getGlossaryAccess().getTermRelationAssignment_13(), "rule__Glossary__TermRelationAssignment_13");
					put(grammarAccess.getRefGlossaryTypeAccess().getRefTypeAssignment_0(), "rule__RefGlossaryType__RefTypeAssignment_0");
					put(grammarAccess.getRefGlossaryTypeAccess().getRefsAssignment_1_1(), "rule__RefGlossaryType__RefsAssignment_1_1");
					put(grammarAccess.getGlossaryTypeAccess().getTypeAssignment(), "rule__GlossaryType__TypeAssignment");
					put(grammarAccess.getTermRelationAccess().getTypeAssignment_1(), "rule__TermRelation__TypeAssignment_1");
					put(grammarAccess.getTermRelationAccess().getTermAssignment_2(), "rule__TermRelation__TermAssignment_2");
					put(grammarAccess.getTermAccess().getRefTermAssignment_0(), "rule__Term__RefTermAssignment_0");
					put(grammarAccess.getTermAccess().getRefsAssignment_1_1(), "rule__Term__RefsAssignment_1_1");
					put(grammarAccess.getStakeholderAccess().getIdAssignment_1(), "rule__Stakeholder__IdAssignment_1");
					put(grammarAccess.getStakeholderAccess().getNameAssignment_4(), "rule__Stakeholder__NameAssignment_4");
					put(grammarAccess.getStakeholderAccess().getTypeAssignment_6(), "rule__Stakeholder__TypeAssignment_6");
					put(grammarAccess.getStakeholderAccess().getCategoryAssignment_8(), "rule__Stakeholder__CategoryAssignment_8");
					put(grammarAccess.getStakeholderAccess().getDescriptionAssignment_9_1(), "rule__Stakeholder__DescriptionAssignment_9_1");
					put(grammarAccess.getStakeholderAccess().getPartOfAssignment_10_1(), "rule__Stakeholder__PartOfAssignment_10_1");
					put(grammarAccess.getGoalAccess().getIdAssignment_1(), "rule__Goal__IdAssignment_1");
					put(grammarAccess.getGoalAccess().getDescriptionAssignment_4(), "rule__Goal__DescriptionAssignment_4");
					put(grammarAccess.getGoalAccess().getStakeholderAssignment_6(), "rule__Goal__StakeholderAssignment_6");
					put(grammarAccess.getGoalAccess().getPriorityAssignment_8(), "rule__Goal__PriorityAssignment_8");
					put(grammarAccess.getGoalAccess().getDependsOnAssignment_9(), "rule__Goal__DependsOnAssignment_9");
					put(grammarAccess.getGoalAccess().getComposedByAssignment_10(), "rule__Goal__ComposedByAssignment_10");
					put(grammarAccess.getDependsOnGoalAccess().getTypeAssignment_0(), "rule__DependsOnGoal__TypeAssignment_0");
					put(grammarAccess.getDependsOnGoalAccess().getRefGoalAssignment_1(), "rule__DependsOnGoal__RefGoalAssignment_1");
					put(grammarAccess.getComposedByAccess().getTypeAssignment_1(), "rule__ComposedBy__TypeAssignment_1");
					put(grammarAccess.getComposedByAccess().getRefGoalAssignment_2(), "rule__ComposedBy__RefGoalAssignment_2");
					put(grammarAccess.getEntityAccess().getIdAssignment_1(), "rule__Entity__IdAssignment_1");
					put(grammarAccess.getEntityAccess().getNameAssignment_4(), "rule__Entity__NameAssignment_4");
					put(grammarAccess.getEntityAccess().getDescriptionAssignment_6(), "rule__Entity__DescriptionAssignment_6");
					put(grammarAccess.getEntityAccess().getAttributesAssignment_7(), "rule__Entity__AttributesAssignment_7");
					put(grammarAccess.getAttributeAccess().getNameAssignment_3(), "rule__Attribute__NameAssignment_3");
					put(grammarAccess.getAttributeAccess().getDescritionAssignment_5(), "rule__Attribute__DescritionAssignment_5");
					put(grammarAccess.getAttributeAccess().getTypeAssignment_7(), "rule__Attribute__TypeAssignment_7");
					put(grammarAccess.getAttributeAccess().getFieldAssignment_8(), "rule__Attribute__FieldAssignment_8");
					put(grammarAccess.getAttributeAccess().getReferenceAssignment_9(), "rule__Attribute__ReferenceAssignment_9");
					put(grammarAccess.getFieldAccess().getSizeAssignment_3(), "rule__Field__SizeAssignment_3");
					put(grammarAccess.getFieldAccess().getMultiplicityAssignment_5(), "rule__Field__MultiplicityAssignment_5");
					put(grammarAccess.getFieldAccess().getDefaultValueAssignment_7(), "rule__Field__DefaultValueAssignment_7");
					put(grammarAccess.getReferenceAccess().getRefToAssignment_1(), "rule__Reference__RefToAssignment_1");
					put(grammarAccess.getReferenceAccess().getMultiplicityAssignment_3(), "rule__Reference__MultiplicityAssignment_3");
					put(grammarAccess.getRefAttributeAccess().getRefAttrAssignment_0(), "rule__RefAttribute__RefAttrAssignment_0");
					put(grammarAccess.getRefAttributeAccess().getRefsAssignment_1_1(), "rule__RefAttribute__RefsAssignment_1_1");
					put(grammarAccess.getActorAccess().getIdAssignment_1(), "rule__Actor__IdAssignment_1");
					put(grammarAccess.getActorAccess().getNameAssignment_4(), "rule__Actor__NameAssignment_4");
					put(grammarAccess.getActorAccess().getTypeAssignment_6(), "rule__Actor__TypeAssignment_6");
					put(grammarAccess.getActorAccess().getDescriptionAssignment_8(), "rule__Actor__DescriptionAssignment_8");
					put(grammarAccess.getActorAccess().getStakeholderAssignment_9_1(), "rule__Actor__StakeholderAssignment_9_1");
					put(grammarAccess.getActorAccess().getDependsOnAssignment_10(), "rule__Actor__DependsOnAssignment_10");
					put(grammarAccess.getDependsOnActorAccess().getTypeAssignment_0(), "rule__DependsOnActor__TypeAssignment_0");
					put(grammarAccess.getDependsOnActorAccess().getStakeholderAssignment_1(), "rule__DependsOnActor__StakeholderAssignment_1");
					put(grammarAccess.getUseCaseAccess().getIdAssignment_1(), "rule__UseCase__IdAssignment_1");
					put(grammarAccess.getUseCaseAccess().getNameAssignment_4(), "rule__UseCase__NameAssignment_4");
					put(grammarAccess.getUseCaseAccess().getTypeAssignment_6(), "rule__UseCase__TypeAssignment_6");
					put(grammarAccess.getUseCaseAccess().getDescriptionAssignment_8(), "rule__UseCase__DescriptionAssignment_8");
					put(grammarAccess.getUseCaseAccess().getPriotityAssignment_10(), "rule__UseCase__PriotityAssignment_10");
					put(grammarAccess.getUseCaseAccess().getGoalsAssignment_12(), "rule__UseCase__GoalsAssignment_12");
					put(grammarAccess.getUseCaseAccess().getFrsAssignment_14(), "rule__UseCase__FrsAssignment_14");
					put(grammarAccess.getUseCaseAccess().getActorInitiatesAssignment_16(), "rule__UseCase__ActorInitiatesAssignment_16");
					put(grammarAccess.getUseCaseAccess().getActorParticipatesAssignment_18(), "rule__UseCase__ActorParticipatesAssignment_18");
					put(grammarAccess.getUseCaseAccess().getPreConditionsAssignment_20(), "rule__UseCase__PreConditionsAssignment_20");
					put(grammarAccess.getUseCaseAccess().getPostConditionsAssignment_22(), "rule__UseCase__PostConditionsAssignment_22");
					put(grammarAccess.getUseCaseAccess().getIncludesAssignment_24(), "rule__UseCase__IncludesAssignment_24");
					put(grammarAccess.getFRAccess().getIdAssignment_1(), "rule__FR__IdAssignment_1");
					put(grammarAccess.getFRAccess().getNameAssignment_4(), "rule__FR__NameAssignment_4");
					put(grammarAccess.getFRAccess().getDescriptionAssignment_6(), "rule__FR__DescriptionAssignment_6");
					put(grammarAccess.getFRAccess().getModalityTypeAssignment_8(), "rule__FR__ModalityTypeAssignment_8");
					put(grammarAccess.getFRAccess().getActionTypeAssignment_10(), "rule__FR__ActionTypeAssignment_10");
					put(grammarAccess.getFRAccess().getSourceAssignment_12(), "rule__FR__SourceAssignment_12");
					put(grammarAccess.getFRAccess().getPriorityAssignment_14(), "rule__FR__PriorityAssignment_14");
					put(grammarAccess.getNFRAccess().getIdAssignment_1(), "rule__NFR__IdAssignment_1");
					put(grammarAccess.getNFRAccess().getNameAssignment_4(), "rule__NFR__NameAssignment_4");
					put(grammarAccess.getNFRAccess().getDescriptionAssignment_6(), "rule__NFR__DescriptionAssignment_6");
					put(grammarAccess.getNFRAccess().getTypeAssignment_8(), "rule__NFR__TypeAssignment_8");
					put(grammarAccess.getNFRAccess().getSubTypeAssignment_10(), "rule__NFR__SubTypeAssignment_10");
					put(grammarAccess.getNFRAccess().getMetricAssignment_12(), "rule__NFR__MetricAssignment_12");
					put(grammarAccess.getNFRAccess().getValueAssignment_14(), "rule__NFR__ValueAssignment_14");
					put(grammarAccess.getNFRAccess().getSourceAssignment_16(), "rule__NFR__SourceAssignment_16");
					put(grammarAccess.getNFRAccess().getPriorityAssignment_18(), "rule__NFR__PriorityAssignment_18");
					put(grammarAccess.getRefGoalAccess().getRefGoalAssignment_0(), "rule__RefGoal__RefGoalAssignment_0");
					put(grammarAccess.getRefGoalAccess().getRefsAssignment_1_1(), "rule__RefGoal__RefsAssignment_1_1");
					put(grammarAccess.getRefFRAccess().getRefFRAssignment_0(), "rule__RefFR__RefFRAssignment_0");
					put(grammarAccess.getRefFRAccess().getRefsAssignment_1_1(), "rule__RefFR__RefsAssignment_1_1");
					put(grammarAccess.getRefUCAccess().getRefUCAssignment_0(), "rule__RefUC__RefUCAssignment_0");
					put(grammarAccess.getRefUCAccess().getRefsAssignment_1_1(), "rule__RefUC__RefsAssignment_1_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			rslingo.rslil.ui.contentassist.antlr.internal.InternalRSLILParser typedParser = (rslingo.rslil.ui.contentassist.antlr.internal.InternalRSLILParser) parser;
			typedParser.entryRuleModel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public RSLILGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(RSLILGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
