/*
 * generated by Xtext
 */
package rslingo.rslil.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import rslingo.rslil.services.RSLILGrammarAccess;

public class RSLILParser extends AbstractContentAssistParser {
	
	@Inject
	private RSLILGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected rslingo.rslil.ui.contentassist.antlr.internal.InternalRSLILParser createParser() {
		rslingo.rslil.ui.contentassist.antlr.internal.InternalRSLILParser result = new rslingo.rslil.ui.contentassist.antlr.internal.InternalRSLILParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getModelAccess().getGroup(), "rule__Model__Group__0");
					put(grammarAccess.getSystemAccess().getGroup(), "rule__System__Group__0");
					put(grammarAccess.getSystemAccess().getGroup_9(), "rule__System__Group_9__0");
					put(grammarAccess.getSystemAccess().getGroup_10(), "rule__System__Group_10__0");
					put(grammarAccess.getRefSystemAccess().getGroup(), "rule__RefSystem__Group__0");
					put(grammarAccess.getRefSystemAccess().getGroup_1(), "rule__RefSystem__Group_1__0");
					put(grammarAccess.getGlossaryAccess().getGroup(), "rule__Glossary__Group__0");
					put(grammarAccess.getStakeholderAccess().getGroup(), "rule__Stakeholder__Group__0");
					put(grammarAccess.getGoalAccess().getGroup(), "rule__Goal__Group__0");
					put(grammarAccess.getModelAccess().getSystemsAssignment_0(), "rule__Model__SystemsAssignment_0");
					put(grammarAccess.getModelAccess().getGlossariesAssignment_1(), "rule__Model__GlossariesAssignment_1");
					put(grammarAccess.getModelAccess().getStakeholdersAssignment_2(), "rule__Model__StakeholdersAssignment_2");
					put(grammarAccess.getModelAccess().getGoalsAssignment_3(), "rule__Model__GoalsAssignment_3");
					put(grammarAccess.getSystemAccess().getIdAssignment_1(), "rule__System__IdAssignment_1");
					put(grammarAccess.getSystemAccess().getSystemIdAssignment_4(), "rule__System__SystemIdAssignment_4");
					put(grammarAccess.getSystemAccess().getNameAssignment_6(), "rule__System__NameAssignment_6");
					put(grammarAccess.getSystemAccess().getDescriptionAssignment_8(), "rule__System__DescriptionAssignment_8");
					put(grammarAccess.getSystemAccess().getRefSystemAssignment_9_1(), "rule__System__RefSystemAssignment_9_1");
					put(grammarAccess.getSystemAccess().getPartOfAssignment_10_1(), "rule__System__PartOfAssignment_10_1");
					put(grammarAccess.getRefSystemAccess().getRefSystemAssignment_0(), "rule__RefSystem__RefSystemAssignment_0");
					put(grammarAccess.getRefSystemAccess().getRefsAssignment_1_1(), "rule__RefSystem__RefsAssignment_1_1");
					put(grammarAccess.getGlossaryAccess().getIdAssignment_1(), "rule__Glossary__IdAssignment_1");
					put(grammarAccess.getGlossaryAccess().getNameAssignment_4(), "rule__Glossary__NameAssignment_4");
					put(grammarAccess.getGlossaryAccess().getTypeAssignment_6(), "rule__Glossary__TypeAssignment_6");
					put(grammarAccess.getGlossaryAccess().getAcronymAssignment_8(), "rule__Glossary__AcronymAssignment_8");
					put(grammarAccess.getGlossaryAccess().getDescriptionAssignment_10(), "rule__Glossary__DescriptionAssignment_10");
					put(grammarAccess.getGlossaryAccess().getPosAssignment_12(), "rule__Glossary__PosAssignment_12");
					put(grammarAccess.getGlossaryAccess().getSynsetAssignment_14(), "rule__Glossary__SynsetAssignment_14");
					put(grammarAccess.getGlossaryAccess().getTermRelationTypeAssignment_16(), "rule__Glossary__TermRelationTypeAssignment_16");
					put(grammarAccess.getGlossaryAccess().getTermRelationAssignment_18(), "rule__Glossary__TermRelationAssignment_18");
					put(grammarAccess.getStakeholderAccess().getIdAssignment_1(), "rule__Stakeholder__IdAssignment_1");
					put(grammarAccess.getStakeholderAccess().getNameAssignment_4(), "rule__Stakeholder__NameAssignment_4");
					put(grammarAccess.getStakeholderAccess().getTypeAssignment_6(), "rule__Stakeholder__TypeAssignment_6");
					put(grammarAccess.getStakeholderAccess().getCategoryAssignment_8(), "rule__Stakeholder__CategoryAssignment_8");
					put(grammarAccess.getStakeholderAccess().getDescriptionAssignment_10(), "rule__Stakeholder__DescriptionAssignment_10");
					put(grammarAccess.getStakeholderAccess().getDependsOnTypeAssignment_12(), "rule__Stakeholder__DependsOnTypeAssignment_12");
					put(grammarAccess.getStakeholderAccess().getDependsOnAssignment_14(), "rule__Stakeholder__DependsOnAssignment_14");
					put(grammarAccess.getGoalAccess().getIdAssignment_1(), "rule__Goal__IdAssignment_1");
					put(grammarAccess.getGoalAccess().getDescriptionAssignment_4(), "rule__Goal__DescriptionAssignment_4");
					put(grammarAccess.getGoalAccess().getStakeholderAssignment_6(), "rule__Goal__StakeholderAssignment_6");
					put(grammarAccess.getGoalAccess().getPriorityAssignment_8(), "rule__Goal__PriorityAssignment_8");
					put(grammarAccess.getGoalAccess().getDependsOnTypeAssignment_10(), "rule__Goal__DependsOnTypeAssignment_10");
					put(grammarAccess.getGoalAccess().getDependsOnAssignment_12(), "rule__Goal__DependsOnAssignment_12");
					put(grammarAccess.getGoalAccess().getComposedByTypeAssignment_14(), "rule__Goal__ComposedByTypeAssignment_14");
					put(grammarAccess.getGoalAccess().getComposedByAssignment_16(), "rule__Goal__ComposedByAssignment_16");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			rslingo.rslil.ui.contentassist.antlr.internal.InternalRSLILParser typedParser = (rslingo.rslil.ui.contentassist.antlr.internal.InternalRSLILParser) parser;
			typedParser.entryRuleModel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public RSLILGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(RSLILGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
